# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    blogMediaDir: '%kernel.project_dir%/../public_html/blog/media'
    archiveMediaDir: '%kernel.project_dir%/../bearsoftArchive'
    archiveTempMediaDir: '%kernel.project_dir%/../bearsoftArchive/temp'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Jdate:
        class: App\Service\Jdate
    Log:
        class: App\Service\Log
        arguments: [ "@doctrine.orm.entity_manager" ]
    SMS:
        class: App\Service\SMS
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
    Provider:
        class: App\Service\Provider
        arguments: [ "@doctrine.orm.entity_manager" ]
    Blog:
        class: App\Service\Blog
        arguments: [ "@doctrine.orm.entity_manager" ]
    twigFunctions:
        class: App\Service\twigFunctions
        arguments: [ "@doctrine.orm.entity_manager" ]
    Access:
        class: App\Service\Access
        arguments: [ "@doctrine.orm.entity_manager","@Symfony.Component.Security.Core.Authentication.Token.Storage.TokenStorageInterface","@Symfony.Component.HttpFoundation.RequestStack" ]